"""add page_content table

Revision ID: 52bae9258a8d
Revises: 087d3f021323
Create Date: 2026-08-27 07:02:18.726339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '52bae9258a8d'
down_revision: Union[str, None] = '087d3f021323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_key', sa.String(length=50), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_content_page_key'), 'page_content', ['page_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_page_content_page_key'), table_name='page_content')
    op.drop_table('page_content')
    # ### end Alembic commands ###
